language: go

os: linux
arch: s390x

# Whenever the Go version is updated here, .circleci/config.yml and .promu.yml
# should also be updated.
go:
- 1.13.x

go_import_path: github.com/prometheus/prometheus

# This ensures that the local cache is filled before running the CI.
# travis_retry retries the command 3 times if it fails as we've experienced
# random issues on Travis.
before_install:
- travis_retry make deps
#Install nvm
- sudo apt-get update && sudo apt-get install -y build-essential libssl-dev
- curl https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
- export NVM_DIR="$HOME/.nvm"
- . $HOME/.nvm/nvm.sh
- nvm install stable
- nvm use stable
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make; fi

script:
#install yarn
- wget https://nodejs.org/dist/v8.9.4/node-v8.9.4-linux-s390x.tar.gz
- tar xzf node-v8.9.4-linux-s390x.tar.gz
- npm install -g yarn@1.2.1
#
- make check_license style unused test lint
- git diff --exit-code
